spring:
  application:
    name: api-gateway
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
    web-application-type: reactive
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment-service
          uri: http://localhost:8788
          predicates:
            - Path=/api/v1/payment/**
logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info
    org.springframework.cloud.gateway: trace
    org.springframework.security: DEBUG
server:
  port: 8080
  forward-headers-strategy: framework
cors:
  allowCredentials: false
  allowedOrigins: http://localhost:4200,http://127.0.0.1:5500
  allowedMethods: GET,POST,PUT,DELETE,OPTIONS,HEAD
  allowedHeaders: origin,content-type,accept,authorization,cookie